package at.aau.project.weatherawsbackendreporter.entity;

import at.aau.project.weatherawsbackendreporter.model.SkyState;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.sql.Timestamp;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "Measurement")
@DynamoDBTable(tableName = "Measurement")
public class Measurement {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @DynamoDBAttribute
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location", referencedColumnName = "location")
    private TemperatureMeasurementPoint temperatureMeasurementPoint;
    @DynamoDBAttribute
    private Timestamp timestamp;
    @DynamoDBAttribute
    private Double temperature;
    @DynamoDBAttribute
    private Integer humidity;
    @DynamoDBAttribute
    private Double pressure;
    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private SkyState sky;

    public Measurement(TemperatureMeasurementPoint point, Timestamp timestamp, Double temperature, Integer humidity, Double pressure, SkyState skyState) {
        this.temperatureMeasurementPoint = point;
        this.timestamp = timestamp;
        this.temperature = temperature;
        this.humidity = humidity;
        this.pressure = pressure;
        this.sky = skyState;
    }
}
